on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: devopsmoc.azurecr.io
        username: ${{ secrets.acr_devopsmoc_username }}
        password: ${{ secrets.acr_devopsmoc_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t devopsmoc.azurecr.io/kube:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push devopsmoc.azurecr.io/kube:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_kube_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep testin | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace testin`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: testin
        container-registry-url: devopsmoc.azurecr.io
        container-registry-username: ${{ secrets.acr_devopsmoc_username }}
        container-registry-password: ${{ secrets.acr_devopsmoc_password }}
        secret-name: kubedockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: testin
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
          manifests/ingress.yml
        images: |
          devopsmoc.azurecr.io/kube:${{ github.sha }}
        imagepullsecrets: |
          kubedockerauth
